# Generated by Django 5.0.2 on 2024-04-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_marca_alter_cor_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="marca",
            name="nome",
            field=models.CharField(max_length=50),
        ),
    ]
